name: Publish to Github Pages (you still need to enable Github Pages for your project)

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: website

